//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Academy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int id_course { get; set; }
        public int id_user { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
