//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int id_course { get; set; }
        public int id_student { get; set; }
        public Nullable<int> rate_value { get; set; }
        public string comment { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
